### ISSUE TITLE
Generate PDF (pdflatex) with SVG instead of PNG image

### ISSUE THREAD

**Issue by moritzregnier** [timofurrer/pandoc-plantuml-filter#13]
Hi there, 
thanks for your work.

On line [39](https://github.com/timofurrer/pandoc-plantuml-filter/blob/e4db7152c04734e405d1561c2dcd85d6de0df38e/pandoc_plantuml_filter.py#L39) you specify the use of PNG format in combination with latex. 

By installing librsvg and its dependencies I managed to create a PDF with SVG as image output from plantuml. 

```
brew install librsvg
```

On the terminal it produced the following issue: 

```
Warning: Failed to set locale category LC_NUMERIC to en_DE.
Warning: Failed to set locale category LC_TIME to en_DE.
Warning: Failed to set locale category LC_COLLATE to en_DE.
Warning: Failed to set locale category LC_MONETARY to en_DE.
Warning: Failed to set locale category LC_MESSAGES to en_DE.
```

This is solved by exporting a locale that actually exists. In my case: 
```
export LC_ALL=de_DE.UTF-8
```

**Comment by MyriaCore** [comment]
In general, SVG should be used by default IMO. It creates a way crisper image.

**Comment by MyriaCore** [comment]
I mentioned this in [the issue  I submitted for pandoc-mermaid-filter](https://github.com/timofurrer/pandoc-mermaid-filter/issues/14), but I think it's worth mentioning here too.

If we want to keep the default behavior that's there now, another potential solution is to try to read an environment variable that the user might set, and have this override the default behavior. Something like `PLANTUML_FILETYPE`:

```
PLANTUML_FILETYPE=svg            \
pandoc --from gfm --to html5     \
   --filter pandoc-plantuml      \
   -o <name of output>.html <name of input>.md
```

A similar thing is done to specify the mermaid binary in [pandoc-mermaid-filter](https://github.com/timofurrer/pandoc-mermaid-filter/blob/f0e3646166d9de5541d6a38927a308bfb09d6b1c/README.md#usage).

**Comment by Chralu** [comment]
Hi everyone,
thanks for that great tool.

@MyriaCore We could use a pandoc variable to specify `filetype`. That way, variable could be either declared inside document itself or injected through command line :

```
pandoc --from gfm --to html5     \
   --filter pandoc-plantuml      \
   -V plantuml_filetype:svg \
   -o <name of output>.html <name of input>.md
```

**Comment by MyriaCore** [comment]
that's a cool idea, didn't know pandoc had those. They do seem better than using environment vars tbh. 

I've since [forked this](https://github.com/MyriaCore/pandoc-plantuml-filter) to fulfill my needs, but would support this approach for sure.

**Comment by autra** [comment]
For pdf, the format that gives best result for me is eps. Using svg, the shadows are still rasters and it's a bit ugly. Ex with eps (ok-ish, I don't like the font but it's acceptable):

![image](https://user-images.githubusercontent.com/1576598/149948472-72dce4b8-d6bb-4950-bc88-c32115dcaaf5.png)

with svg (a mix between vector and raster graphics... meh...):

![image](https://user-images.githubusercontent.com/1576598/149948611-c0a4c688-fab8-424e-a4c9-447e8559e2f7.png)

Ideally, I'd have the "bob" of the svg format in the square of the eps ;-)

I'd also default to a graphic format for latex, not a png (but a variable like plantuml_filetype is ok for me).

**Comment by autra** [comment]
That being said, on a regular basis, I'll choose a theme that won't have any shadow. In this case, maybe svg is better.
