### ISSUE TITLE
html5 types use .png instead of svg

### ISSUE THREAD

**Issue by rene-aguirre** [timofurrer/pandoc-plantuml-filter#17]
Using `-t html5` on `pandoc` causes to use `png` for plantuml images (which is the default).

IMO, any `pandoc` html like format that supports `--self-contained` would be nice to have it mapped to use `svg` this includes: html4, html5, html+lhs, html5+lhs, s5, slidy, slideous, dzslides, and revealjs.

Please consider adding these formats to the `get_extension` function call parameters mapped to `svg`.

**Comment by Chralu** [comment]
Hi,

that issue could be redundant with #13
