### ISSUE TITLE
Publish current code to PyPI

### ISSUE THREAD

**Issue by ojob** [timofurrer/pandoc-plantuml-filter#20]
Hello,
I'm using this filter and really appreciate its functionality, and the fact that it works seamlessly, thanks a lot!
I see some nice additions since [0.1.2, last published to PyPI][1], but I also really need to pin down the version used.

So, would you please consider publishing a 0.1.3 to PyPI ? That would be greatly appreciated!

Best Regards,

[1]: https://pypi.org/project/pandoc-plantuml-filter/#history

**Comment by fliiiix** [comment]
took a while but here we are 

![image](https://github.com/timofurrer/pandoc-plantuml-filter/assets/1682954/229c296e-bda1-4022-88d9-9a125aaec408)
