### ISSUE TITLE
Illogical Directories for Included Files

### ISSUE THREAD

**Issue by 7enderhead** [timofurrer/pandoc-plantuml-filter#31]
- You can include other Plantuml files with the `!include x.puml` syntax:
```pandoc
```plantuml
!include other.puml
Bob -> Alice: use stuff from other.puml
```#end
```
- Running pandoc with pandoc-plantuml-filter in directory where the markdown and the included Plantuml files are located.
- The filter creates a plantuml-images subdirectory and seems to work only there. The included files are therefore not found.
- Linking/copying the include files into the plantuml-images makes the mechanism work.
- But this seems illogical. The files should automatically be used from the base directory.

**Comment by fliiiix** [comment]
I wasn't aware that including a plantuml into a plantuml is a thing so looking at this seems like a bug. Thanks for reporting! 
I'm personally not going to fix that anytime soon since i don't use that for my use-case.

But happy to help someone to fix it, review and release it.

**Comment by Felixoid** [comment]
I personally vote against putting garbage or `plantuml-images` into the root of the pandoc "project"

The mess comes very quickly if there is WiP, and finding anything useful becomes very tricky

**Comment by 7enderhead** [comment]
> I personally vote against putting garbage or `plantuml-images` into the root of the pandoc "project"
> 
> The mess comes very quickly if there is WiP, and finding anything useful becomes very tricky

This is not what I was suggesting. Plantum processing should stay in the plantuml-images subdirectory, but the process should take into account the files in the main directory.

**Comment by Felixoid** [comment]
mnerm... What about simply trying `!include ../other.puml`?

It's impossible "to stay in the plantuml-images subdirectory, but the process should take into account the files in the main directory". The included files are either in one or another directory. In other cases, they must be symlinked into the images directory.

**Comment by 7enderhead** [comment]
> mnerm... What about simply trying `!include ../other.puml`?
> 
> It's impossible "to stay in the plantuml-images subdirectory, but the process should take into account the files in the main directory". The included files are either in one or another directory. In other cases, they must be symlinked into the images directory.

This would mess up markdown previews in, e.g., Visual Studio Code. It is also not "correct". If the files are in the same folder, why should the include statement point one level up?

I'm also not quite sure what you mean by "it's impossible". Why would the process not be able to work in its subfolder but still have access to and use the files from the original folder?

**Comment by Felixoid** [comment]
Well, get to the plantuml-images and call ls. That's what you have there. Now call "ls ..", and that's what you have I parent dir.

If you need files from parent dir, you use "../" as prefix. That's how it works with files on disk.

**Comment by 7enderhead** [comment]
> Well, get to the plantuml-images and call ls. That's what you have there. Now call "ls ..", and that's what you have I parent dir.
> 
> If you need files from parent dir, you use "../" as prefix. That's how it works with files on disk.

Yes, but should the internal implementation detail that a subfolder is used for storing files be visible in the source code of the diagram? Seems like questionable design to me. And thanks for enlightening me on the workings of folders/subfolders and what the ls command ist used for, this seems like a very friendly place.

**Comment by Felixoid** [comment]
You ask for the process considering files from the parent directory as they are from the pwd. And look very surprised, why it's not possible. If you're aware of how ls works, why do you expect something else from any other process?

It can't consider files from the parent directory as in the pwd, because files do not exist. And the process working from plantuml-images see the FS from that point.

**Comment by 7enderhead** [comment]
Let's be creative here. Why not simply rewrite (relative) `!include xyz.puml` paths as `!include ../xyz.puml`. You seem to extract the uml sources anyway. Bonus feature: include the included file(s) in the fingerprint that you use to decide whether recreation of the picture has to be done.

**Comment by Felixoid** [comment]
So, you ask for other people having backward incompatible changes with implicit rewriting their UML sources. 

I'd say, first open your diagram source in `plantuml-images`, show its content, show the project structure, and command `plantuml` that produces what you want.

**Comment by 7enderhead** [comment]
I don't ask anybody to do anything. I was trying to give valuable feedback on a usage scenario of your filter. It does not seem to be too common for people to use Plantuml `include` files in a pandoc scenario, otherwise many people would have found at least "things that don't work out of the box without knowing how the filter performs its work".

I respect that you have a different view on your filter regarding of what is an obviously intrinsic part of how it works and what a user should know about this design aspect (i.e., that there is a plantuml-images folder into which the Plantuml sources are being extracted and that this is the working folder for the filter when invoking Plantuml), versus a more black-box approach in my idealistic view (i.e., that I don't care how Plantuml diagrams show up in the final document and that from the perspective of the pandoc document, paths are seen relative to the pandoc input).

I can cope with the situation. It amounts to the command `ln *.puml ./plantuml-images/` once during setup of a pandoc folder or again if there is a new included Plantuml file. I will close this issue. It is obvious that no progress will be made here.

**Comment by Felixoid** [comment]
It's not "my filter".

I tried to triage your request and get an idea of how the solution should work from your point of view.

Symlinks were proposed in https://github.com/timofurrer/pandoc-plantuml-filter/issues/31#issuecomment-2419231513, and they look like the easiest way. 

Another way to fix it is using `../` prefix in include explicitly. I don't follow your inconvenience of this approach.

Both solutions above are much easier than creative backward incompatible changes.
