### ISSUE TITLE
Fix publish to pip

### ISSUE THREAD

**Issue by fliiiix** [timofurrer/pandoc-plantuml-filter#7]
Is there a reason [this fix]( https://github.com/timofurrer/pandoc-plantuml-filter/commit/1b3c6b2d997faed40c0ec2e754f88e57366bba00 ) is not released to pip?

**Comment by RonanHiggins** [comment]
Is this something I should do @fliiiix

**Comment by timofurrer** [comment]
No reason. Can do so later.
@RonanHiggins Thanks for the help - I'll do that though, as it requires permissions to pypi ;)

**Comment by timofurrer** [comment]
Just released *v0.1.2* to pypi.

**Comment by fliiiix** [comment]
Thanks @timofurrer for releasing it :+1: and @RonanHiggins for the fix!
